### ISSUE TITLE
No need for SafeMath any more

### ISSUE THREAD

**Issue by cliffhall** [MaxflowO2/ERC2981#1]
https://github.com/MaxflowO2/ERC2981/blob/010744cac3e6c5214a184733faa59cca61884daa/contracts/ERC2981.sol#L21

This has been[ obviated by language changes](
https://docs.soliditylang.org/en/v0.8.7/control-structures.html?highlight=checked#checked-or-unchecked-arithmetic)

> Since Solidity 0.8.0, all arithmetic operations revert on over- and underflow by default, thus making the use of these libraries unnecessary.

Also there is [discussion about removing it from OZ](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2465) entirely, the only good reasons to keep it being backward compatibility and potential use in unchecked blocks. 

Nevertheless, not something we should propagate with new works.

**Comment by MaxflowO2** [comment]
Actually that’s the only reason why I have it in there, but looking forward and not backwards you are right, I’ll update this.
