### ISSUE TITLE
Reconsider use of ERC165Storage

### ISSUE THREAD

**Issue by cliffhall** [MaxflowO2/ERC2981#3]
https://github.com/MaxflowO2/ERC2981/blob/010744cac3e6c5214a184733faa59cca61884daa/contracts/ERC2981.sol#L20

While an example in the ERC did use the `ERC165Storage.registerInterface()` method, it should be optional in a framework. In an architecture that uses other methods for managing supported interfaces this contract will not be used.

Particularly in the case of proxied contracts (which almost all of any import will be) and especially ERC2535 Diamonds, ERC165Storage is no good because it does not write to a unique storage slot. Even the ['upgradable' version](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/utils/introspection/ERC165StorageUpgradeable.sol) does not do this, and so its storage in a fine-grained proxy like the diamond which allows multiple implementation contracts (called facets) to supply functions, if any other contract fails to put all its data in a targeted, unique slot, it will conflict with the data in ERC165Storage's slot.

In short it is much better to simply implement `supportsInterface` and allow descendant contracts to determine how to handle management of supported interfaces. Such contract can decide to use ERC165Storage if it wants, and register all the interfaces it supports in one go (similar to how the example in the 2981 spec has it).

I just built such a system for Seen.Haus marketplace, with different kinds of proxies including Diamond, and each required its own approach to managing and supported interfaces. Those were best handled at the final descendant.

**Comment by MaxflowO2** [comment]
Sounds good, honestly this was a toss up for me as well. I’ll take a look at ERC2535 a bit more in depth as well. Been using ERC165 more heavily than others. Thank you for the updates! I’ll post a new commit soon with the suggestions.

**Comment by MaxflowO2** [comment]
@cliffhall was thinking about this long and deep during my past two launches today on smaller projects. Would you suggest an override of `supportsInterface`, or just declare the variable so the end state can call it?

**Comment by cliffhall** [comment]
I highly suggest overriding `supportsInterface` since using storage variables can adversely affect data integrity when used with some proxy patterns, particularly the Diamond, where all logic contracts need to use unique slots and not the contract-defined storage slots you get when defining a state variable.

NFT contracts are important to proxy, because if the logic needs an upgrade (e.g., to fix a vulnerability) if not proxied, you're stuck with the deployed code and there's little more you can do than burn the old tokens and issue them to their current owners on a new contract, thereby disrupting the provenance chain. I've built it into Seen.Haus marketplace's new contract suite and can say definitively I would not inherit code that uses state variables if there was any way to avoid it. 

You don't really see what a pain it is to inherit from different contracts that define storage variables until you try to proxy them. 

- In a simple **proxy => single logic contract** scenario, the logic contract can feel free to use storage variables that aren't in a unique slot, but if you upgrade the logic, you have to be very careful not to break the existing storage layout in the proxy. If you delete a variable or add one somewhere other than as the very last variable definition, then the new storage slots will not map to the old ones and you will most likely experience unexpected failures during operation. 
- In a **diamond proxy => multiple logic contract** scenario, the problem is amplified because all the facets (which can be upgraded independently) need to agree on the storage layout in the proxy. Here it is imperative that the data each facet works with be stored in one or more unique slots. If two facets inherit different third party contracts that use storage variables, they will absolutely conflict with each other, even if the inheriting contract is putting all of its defined data into a unique slot.

What I'm saying here is don't write code that's intended to be inherited unless you use a specific storage slot and not just variables defined at the top of the contract. It makes life a pain for developers of NFTs who want upgradeability.

If you absolutely must use storage, define a unique storage slot and put your data into it. Provide a getter that inheriting contracts can use.

A simple example:

`OurSpecialFramework.Sol`
```
abstract contract OurSpecialFramework {

    bytes32 constant OUR_SPECIAL_FRAMEWORK_DATA_POSITION = keccak256("our.special.framework.data");

    struct OurSpecialFrameworkData {

        // Pause flag
        bool paused;

        // Contract owner
        address owner;

        // Number of elves
        uint256 elfCount;    

    }

    function getOurSpecialFrameworkData() internal pure returns (OurSpecialFrameworkData storage osfd) {
        bytes32 position = OUR_SPECIAL_FRAMEWORK_DATA_POSITION;
        assembly {
            osfd.slot := position
        }
    }

   ...
}
```

`MyLogicContract.Sol`
```
contract MyLogicContract is OurSpecialFramework {

    function getElfCount() public view returns (uint256) {
        OurSpecialFrameworkData storage osfd = getOurSpecialFrameworkData();
        return osfd.elfCount;
    }

}
```

In this case the inherited contract uses a unique slot defined in `OUR_SPECIAL_FRAMEWORK_DATA_POSITION` which will not conflict with other variables in the inherited contract, and so would be exactly what you want to see if you're planning to proxy `MyLogicContract`.

However, that's also more of a pain to implement than simply overriding `supportsInterface`, if that's all you need to do. Let the implementer decide if they want to use ERC165Storage or an equivalent implementation of their own. It affords them the most latitude in their architectural decisions.

**Comment by MaxflowO2** [comment]
@cliffhall got to admit, ever since reading up on all this, and with your interventions, think you made me a better solidity developer. Completely understand now, like with amazing clarity what you mean. After reading about Diamond, then seeing how it's implemented with your case example of just proxy of one, didn't fully comprehend what I was doing with it until now.

Just like any NFT project, an immense amount of planning needs to be undertaken, just to ensure production, and product viability, let alone the metadata.

Really do appreciate this, but last question, should that override be here or in that final constructor?

Also using this logic, will be breaking this into sub-projects as you see with issue #4. No need for a blanket statement, when there's multiple case uses.

**Comment by cliffhall** [comment]
> Really do appreciate this, but last question, should that override be here or in that final constructor?

Not sure what you mean by overriding in a constructor?

I would just extend `ERC165` instead of `ERC165Storage`in your ERC2981 contract, then override the inherited `supportsInterface` method to return true when checking for ERC2981 or ERC165 support.

**Comment by MaxflowO2** [comment]
> > Really do appreciate this, but last question, should that override be here or in that final constructor?
> 
> Not sure what you mean by overriding in a constructor?
> 
> I would just extend `ERC165` instead of `ERC165Storage`in your ERC2981 contract, then override the inherited `supportsInterface` method to return true when checking for ERC2981 or ERC165 support.
> 
> ```
>     /**
>      * @notice Implementation of the {IERC165} interface.
>      */
>     function supportsInterface(bytes4 interfaceId)
>     public
>     view
>     override(ERC165)
>     returns (bool)
>     {
>         return (
>             interfaceId == type(IERC165).interfaceId ||
>             interfaceId == type(IERC2981).interfaceId
>         );
>     }
> ```

This is where I've ended up, honestly. Still going to do a couple of tweaks in the near future, but should have a v2.1.1 rollout with this and ownable correction to push, push-pull, and push-pull/decline options.
